# .github/workflows/update-macdb.yml
name: Update MAC DB CSV

on:
  schedule:
    - cron: '0 19 * * *'  # 毎日 19時(UTC)/04時（JST）
  workflow_dispatch:       # 手動実行可

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # ← これを追加
    steps:
      - uses: actions/checkout@v4

      - name: Download IEEE CSV files
        run: |
          curl --parallel --parallel-immediate \
            -O https://standards-oui.ieee.org/oui/oui.csv \
            -O https://standards-oui.ieee.org/oui28/mam.csv \
            -O https://standards-oui.ieee.org/oui36/oui36.csv \
            -O https://standards-oui.ieee.org/cid/cid.csv \
            -O https://standards-oui.ieee.org/iab/iab.csv
      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add *.csv
          git diff --cached --quiet || git commit -m "Update IEEE CSV $(date '+%Y-%m-%d')"
          git pull --rebase origin main   # ← 追加
          git push
